# Generated by Django 4.0 on 2022-01-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='history_type_name',
            field=models.CharField(choices=[(1, 'Restock'), (2, 'Sell'), (3, 'Manual Adjust')], max_length=50),
        ),
    ]
