# Generated by Django 4.0 on 2022-01-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_producthistory_history_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='history_type_name',
            field=models.CharField(max_length=50),
        ),
    ]
