# Generated by Django 3.2.8 on 2021-11-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniqueId', models.UUIDField()),
                ('Amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('CreatedBy', models.CharField(max_length=250)),
                ('CreatedDate', models.DateTimeField()),
                ('ActionReferenceId', models.UUIDField()),
                ('PayerId', models.UUIDField()),
                ('PaymentMethodId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmethod')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
