# Generated by Django 4.0.1 on 2022-02-01 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('order_status_id', models.IntegerField(choices=[(1, 'Created'), (2, 'Pending Payment'), (3, 'Complete')], default=1)),
                ('order_status_name', models.CharField(default='Created', max_length=50)),
                ('before_discount_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('promotion_discount_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('net_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_by', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('payment_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.payment')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shops.shop')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('product_base_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('actual_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
