# Generated by Django 4.0 on 2022-01-02 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '__first__'),
        ('products', '__first__'),
        ('payments', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('before_discount_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('promotion_discount_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('net_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_by', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.payment')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('qty', models.IntegerField()),
                ('product_base_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('actual_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
