# Generated by Django 3.2.8 on 2021-11-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_Initial'),
        ('products', '0001_Initial'),
        ('payments', '0001_Initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_transaction_id', models.CharField(max_length=100)),
                ('before_discount_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('promotion_discount_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('net_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_by', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField()),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('payment_transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.payment')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('qty', models.IntegerField()),
                ('product_base_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('actual_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
