# Generated by Django 4.0 on 2022-01-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status_name',
            field=models.CharField(default='Created', max_length=50),
        ),
    ]
