# Generated by Django 4.0 on 2022-01-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status_id',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Pending Payment'), (3, 'Complete')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status_name',
            field=models.CharField(choices=[(1, 'Created'), (2, 'Pending Payment'), (3, 'Complete')], default=1, max_length=50),
        ),
    ]
