# Generated by Django 4.0.1 on 2022-02-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_transaction',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
