# Generated by Django 4.0 on 2022-01-02 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('orders', '0003_rename_qty_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.payment'),
        ),
    ]
