# Generated by Django 3.2.8 on 2021-11-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_transaction_id', models.CharField(max_length=100)),
                ('payment_type_id', models.IntegerField(choices=[(1, 'Order')])),
                ('payment_type_name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_by', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField()),
                ('action_reference_id', models.CharField(max_length=250)),
                ('payer_id', models.UUIDField()),
                ('payment_method_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmethod')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
