# Generated by Django 4.0 on 2022-01-08 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_type_id', models.IntegerField(choices=[(1, 'Order')])),
                ('payment_type_name', models.CharField(choices=[(1, 'Order')], default=1, max_length=50)),
                ('payment_status_id', models.IntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Complete')], default=1)),
                ('payment_status_name', models.CharField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Complete')], default=1, max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_by', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=250, null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('action_reference_id', models.CharField(max_length=250)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
