# Generated by Django 4.0 on 2022-01-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status_name',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type_name',
            field=models.CharField(default='Order', max_length=50),
        ),
    ]
