# Generated by Django 3.2.8 on 2021-11-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Address1', models.CharField(max_length=250)),
                ('Address2', models.CharField(max_length=250)),
                ('AddressPostcode', models.IntegerField()),
                ('AddressCity', models.CharField(max_length=100)),
                ('AddressState', models.CharField(max_length=100)),
                ('OwnerId', models.UUIDField()),
                ('Nickname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shop',
            },
        ),
    ]
