# Generated by Django 3.2.8 on 2021-11-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniqueId', models.UUIDField()),
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactTypeId', models.IntegerField(choices=[(1, 'Mobile Number'), (2, 'Email')])),
                ('ContactTypeName', models.CharField(max_length=50)),
                ('ContactValue', models.CharField(max_length=250)),
                ('CustomerId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
            ],
            options={
                'db_table': 'customer_contact',
            },
        ),
    ]
