# Generated by Django 3.2.8 on 2021-11-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniqueId', models.UUIDField()),
                ('BeforeDiscountPrice', models.DecimalField(decimal_places=4, max_digits=18)),
                ('PromotionDiscountAmount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('NetPrice', models.DecimalField(decimal_places=4, max_digits=18)),
                ('PaymentTransactionId', models.UUIDField()),
                ('CreatedBy', models.CharField(max_length=250)),
                ('CreatedDate', models.DateTimeField()),
                ('BuyerId', models.UUIDField()),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductUniqueId', models.UUIDField()),
                ('ProductName', models.CharField(max_length=250)),
                ('Qty', models.IntegerField()),
                ('ProductBasePrice', models.DecimalField(decimal_places=4, max_digits=18)),
                ('DiscountAmount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('ActualPrice', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
