# Generated by Django 3.2.8 on 2021-11-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('BasePrice', models.DecimalField(decimal_places=4, max_digits=18)),
                ('QtyInStock', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=250)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.CharField(max_length=250)),
                ('UpdatedDate', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HistoryTypeId', models.IntegerField(choices=[(1, 'Restock'), (2, 'Sell'), (3, 'Manual Adjust')])),
                ('HistoryTypeName', models.CharField(max_length=50)),
                ('Qty', models.IntegerField()),
                ('Remark', models.CharField(max_length=250)),
                ('CreatedBy', models.CharField(max_length=250)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ActionReferenceId', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_history',
            },
        ),
    ]
